# Generated by Django 2.1.7 on 2019-03-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='location',
            field=models.CharField(help_text='Enter your location', max_length=100, null=True),
        ),
    ]
