# Generated by Django 2.1.7 on 2019-03-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_blogger_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post',
            field=models.TextField(help_text='Start your blog post here', max_length=5000, null=True),
        ),
    ]
