# Generated by Django 2.1.7 on 2019-03-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_blog_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date_of_blog']},
        ),
        migrations.AddField(
            model_name='blogger',
            name='bio',
            field=models.CharField(help_text='Tell us about yourself', max_length=1000, null=True),
        ),
    ]
